# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: ui
image:
  name: iampaavan/csye-7374-advanced-cloud-webapp-frontend:f91736015e341c789b94810645034423cbd0236a
  pullPolicy: IfNotPresent
imagePullSecrets: regcred
#nameOverride: ""
#fullnameOverride: ""
service:
  name: ui-frontend
  #  bname: api-backend-recipe1
  type: LoadBalancer
  port: 2000
  targetport: 2000
imageCredentials:
  registry: https://index.docker.io/v1/
  username: iampaavan
  password: viratKohli153@
initContainers:
  name: busybox:1.28
backendServiceName: ""
