apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: api
  name: role-{{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "configmaps"]
  verbs: ["get"]
