apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-{{ .Release.Name }}
  namespace: api
subjects:
- kind: ServiceAccount
  name: serviceaccount-{{ .Release.Name }}
  namespace: api
roleRef:
  kind: Role
  name: role-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io