apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-{{ .Release.Name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
